name: CI/CD Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy ENV'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the environment
      run: echo "Deploying to ${{ github.event.inputs.environment }} environment"